<?php
// Set the title if not already set
if (!isset($title)) {
    $title = 'Your Complete Cosmic Blueprint - ' . ($data['birth_date'] ?? 'Unknown Date');
}

// Extract data
$birthDate = $data['birth_date'] ?? '';
$westernZodiac = $data['western_zodiac'] ?? '';
$chineseZodiac = $data['chinese_zodiac'] ?? '';
$rarityScore = $data['rarity_score'] ?? 0;
$cosmicSignificance = $data['cosmic_significance'] ?? '';
$dayInHistory = $data['day_in_history'] ?? [];
$famousTwin = $data['famous_twin'] ?? null;
$slug = $data['slug'] ?? '';

// Premium content (would be generated by AI or from database)
$soulArchetype = $data['soul_archetype'] ?? [
    'name' => 'The Cosmic Wanderer',
    'description' => 'You are a natural explorer of both physical and metaphysical realms, driven by an insatiable curiosity about the mysteries of existence.',
    'traits' => ['Intuitive', 'Adventurous', 'Philosophical', 'Independent'],
    'strengths' => 'Your ability to see beyond the surface and connect seemingly unrelated concepts makes you a natural innovator and spiritual guide.',
    'challenges' => 'Your restless nature may sometimes prevent you from fully committing to one path, leading to scattered energy.'
];

$planetaryInfluence = $data['planetary_influence'] ?? [
    'dominant_planet' => 'Neptune',
    'influence' => 'Neptune\'s mystical energy amplifies your intuitive abilities and connection to the collective unconscious.',
    'secondary_planets' => [
        'Mercury' => 'Enhances your communication of abstract concepts',
        'Jupiter' => 'Expands your philosophical worldview'
    ]
];

$lifePathNumber = $data['life_path_number'] ?? [
    'number' => 7,
    'meaning' => 'The Seeker',
    'description' => 'Your life path is one of spiritual seeking and inner wisdom. You are here to develop your intuition and share deep insights with the world.',
    'career_guidance' => 'Research, teaching, counseling, or any field that allows you to explore and share knowledge.',
    'relationship_guidance' => 'You need partners who respect your need for solitude and intellectual stimulation.'
];
?>

<div class="min-vh-100" style="background: linear-gradient(135deg, #581c87, #1e3a8a, #312e81);">
    <!-- Header -->
    <div class="border-bottom" style="background-color: rgba(0, 0, 0, 0.2); backdrop-filter: blur(8px); border-color: rgba(255, 255, 255, 0.1) !important;">
        <div class="container-fluid" style="max-width: 72rem;">
            <div class="d-flex align-items-center justify-content-between py-3">
                <h1 class="h3 fw-bold text-white mb-0">
                    <span style="background: linear-gradient(45deg, #fbbf24, #f472b6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;">
                        CosmicHub
                    </span>
                </h1>
                <div class="d-flex align-items-center gap-3">
                    <button onclick="downloadPDF()" class="btn text-white d-flex align-items-center px-3 py-2 rounded-3" style="background: linear-gradient(45deg, #10b981, #0d9488); border: none; transition: all 0.3s;">
                        <svg class="me-2" width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                        </svg>
                        Download PDF
                    </button>
                    <a href="/" class="text-decoration-none" style="color: #c4b5fd; transition: color 0.3s;" onmouseover="this.style.color='white'" onmouseout="this.style.color='#c4b5fd'">
                        ← Try Another Date
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid py-4" style="max-width: 72rem;">
        <!-- Unlocked Badge -->
        <div class="text-center mb-4">
            <div class="d-inline-flex align-items-center text-white px-4 py-3 rounded-pill fw-bold fs-5 shadow-lg" style="background: linear-gradient(45deg, #eab308, #ec4899);">
                <span class="fs-3 me-2">🔓</span>
                Complete Cosmic Blueprint Unlocked
            </div>
        </div>

        <!-- Main Blueprint Header -->
        <div class="rounded-4 p-4 shadow-lg border mb-4" style="background-color: rgba(255, 255, 255, 0.1); backdrop-filter: blur(16px); border-color: rgba(255, 255, 255, 0.2) !important;">
            <div class="text-center mb-4">
                <h2 class="display-4 fw-bold text-white mb-3">
                    Your Complete Cosmic Blueprint
                </h2>
                <p class="fs-4 mb-4" style="color: #c4b5fd;">
                    Born on <?php echo htmlspecialchars($birthDate); ?>
                </p>
                
                <!-- Quick Stats -->
                <div class="row g-3">
                    <div class="col-6 col-md-3">
                        <div class="rounded-3 p-3" style="background: linear-gradient(135deg, rgba(147, 51, 234, 0.3), rgba(37, 99, 235, 0.3));">
                            <div class="fs-3 mb-1">♈</div>
                            <div class="small" style="color: #c4b5fd;">Western</div>
                            <div class="fw-bold text-white"><?php echo htmlspecialchars($westernZodiac); ?></div>
                        </div>
                    </div>
                    <div class="col-6 col-md-3">
                        <div class="rounded-3 p-3" style="background: linear-gradient(135deg, rgba(220, 38, 38, 0.3), rgba(236, 72, 153, 0.3));">
                            <div class="fs-3 mb-1">🐉</div>
                            <div class="small" style="color: #c4b5fd;">Chinese</div>
                            <div class="fw-bold text-white"><?php echo htmlspecialchars($chineseZodiac); ?></div>
                        </div>
                    </div>
                    <div class="col-6 col-md-3">
                        <div class="rounded-3 p-3" style="background: linear-gradient(135deg, rgba(202, 138, 4, 0.3), rgba(234, 88, 12, 0.3));">
                            <div class="fs-3 mb-1">💎</div>
                            <div class="small" style="color: #c4b5fd;">Rarity</div>
                            <div class="fw-bold text-white"><?php echo number_format($rarityScore, 1); ?>/10</div>
                        </div>
                    </div>
                    <div class="col-6 col-md-3">
                        <div class="rounded-3 p-3" style="background: linear-gradient(135deg, rgba(22, 163, 74, 0.3), rgba(13, 148, 136, 0.3));">
                            <div class="fs-3 mb-1">🔢</div>
                            <div class="small" style="color: #c4b5fd;">Life Path</div>
                            <div class="fw-bold text-white"><?php echo $lifePathNumber['number']; ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Premium Content Sections -->
        <div class="row g-4 mb-4">
            <!-- Soul's Archetype -->
            <div class="col-lg-6">
                <div class="rounded-4 p-4 shadow-lg border" style="background: linear-gradient(135deg, rgba(147, 51, 234, 0.2), rgba(236, 72, 153, 0.2)); backdrop-filter: blur(16px); border-color: rgba(168, 85, 247, 0.3) !important;">
                    <div class="d-flex align-items-center mb-4">
                        <div class="rounded-circle d-flex align-items-center justify-content-center me-3" style="width: 64px; height: 64px; background: linear-gradient(45deg, #a855f7, #ec4899);">
                            <span class="fs-2">🎭</span>
                        </div>
                        <div>
                            <h3 class="h4 fw-bold text-white mb-1">Soul's Archetype</h3>
                            <p class="mb-0" style="color: #c4b5fd;">Your core personality blueprint</p>
                        </div>
                    </div>
                    
                    <div class="vstack gap-4">
                        <div>
                            <h4 class="h5 fw-bold text-white mb-2"><?php echo htmlspecialchars($soulArchetype['name']); ?></h4>
                            <p class="lh-base" style="color: #e9d5ff;"><?php echo htmlspecialchars($soulArchetype['description']); ?></p>
                        </div>
                        
                        <div>
                            <h5 class="fw-bold text-white mb-2">Core Traits:</h5>
                            <div class="d-flex flex-wrap gap-2">
                                <?php foreach ($soulArchetype['traits'] as $trait): ?>
                                <span class="badge rounded-pill px-3 py-2 small" style="background-color: rgba(168, 85, 247, 0.3); color: #e9d5ff;">
                                    <?php echo htmlspecialchars($trait); ?>
                                </span>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        
                        <div>
                            <h5 class="fw-bold text-white mb-2">Strengths:</h5>
                            <p class="small lh-base" style="color: #e9d5ff;"><?php echo htmlspecialchars($soulArchetype['strengths']); ?></p>
                        </div>
                        
                        <div>
                            <h5 class="fw-bold text-white mb-2">Growth Areas:</h5>
                            <p class="small lh-base" style="color: #e9d5ff;"><?php echo htmlspecialchars($soulArchetype['challenges']); ?></p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Planetary Influence -->
            <div class="col-lg-6">
                <div class="rounded-4 p-4 shadow-lg border" style="background: linear-gradient(135deg, rgba(37, 99, 235, 0.2), rgba(13, 148, 136, 0.2)); backdrop-filter: blur(16px); border-color: rgba(59, 130, 246, 0.3) !important;">
                    <div class="d-flex align-items-center mb-4">
                        <div class="rounded-circle d-flex align-items-center justify-content-center me-3" style="width: 64px; height: 64px; background: linear-gradient(45deg, #60a5fa, #14b8a6);">
                            <span class="fs-2">🪐</span>
                        </div>
                        <div>
                            <h3 class="h4 fw-bold text-white mb-1">Planetary Influence</h3>
                            <p class="mb-0" style="color: #93c5fd;">Celestial forces shaping your destiny</p>
                        </div>
                    </div>
                    
                    <div class="vstack gap-4">
                        <div>
                            <h4 class="h5 fw-bold text-white mb-2">Dominant Planet: <?php echo htmlspecialchars($planetaryInfluence['dominant_planet']); ?></h4>
                            <p class="lh-base" style="color: #dbeafe;"><?php echo htmlspecialchars($planetaryInfluence['influence']); ?></p>
                        </div>
                        
                        <div>
                            <h5 class="fw-bold text-white mb-3">Secondary Influences:</h5>
                            <div class="vstack gap-3">
                                <?php foreach ($planetaryInfluence['secondary_planets'] as $planet => $influence): ?>
                                <div class="rounded-3 p-3" style="background-color: rgba(59, 130, 246, 0.2);">
                                    <div class="fw-semibold" style="color: #93c5fd;"><?php echo htmlspecialchars($planet); ?></div>
                                    <div class="small" style="color: #dbeafe;"><?php echo htmlspecialchars($influence); ?></div>
                                </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Life Path Number -->
        <div class="rounded-4 p-4 shadow-lg border mb-4" style="background: linear-gradient(135deg, rgba(202, 138, 4, 0.2), rgba(234, 88, 12, 0.2)); backdrop-filter: blur(16px); border-color: rgba(251, 191, 36, 0.3) !important;">
            <div class="d-flex align-items-center mb-4">
                <div class="rounded-circle d-flex align-items-center justify-content-center me-3" style="width: 64px; height: 64px; background: linear-gradient(45deg, #fbbf24, #f97316);">
                    <span class="fs-2 fw-bold"><?php echo $lifePathNumber['number']; ?></span>
                </div>
                <div>
                    <h3 class="h4 fw-bold text-white mb-1">Life Path Number: <?php echo $lifePathNumber['number']; ?></h3>
                    <p class="mb-0" style="color: #fde68a;"><?php echo htmlspecialchars($lifePathNumber['meaning']); ?></p>
                </div>
            </div>
            
            <div class="row g-4">
                <div class="col-md-6">
                    <h4 class="h5 fw-bold text-white mb-3">Your Destined Journey</h4>
                    <p class="lh-base mb-4" style="color: #fef3c7;"><?php echo htmlspecialchars($lifePathNumber['description']); ?></p>
                    
                    <h5 class="fw-bold text-white mb-2">Career Guidance:</h5>
                    <p class="small lh-base" style="color: #fef3c7;"><?php echo htmlspecialchars($lifePathNumber['career_guidance']); ?></p>
                </div>
                
                <div class="col-md-6">
                    <h5 class="fw-bold text-white mb-2">Relationship Guidance:</h5>
                    <p class="small lh-base mb-4" style="color: #fef3c7;"><?php echo htmlspecialchars($lifePathNumber['relationship_guidance']); ?></p>
                    
                    <div class="rounded-3 p-3" style="background-color: rgba(245, 158, 11, 0.2);">
                        <h6 class="fw-semibold mb-2" style="color: #fde68a;">Key Life Themes:</h6>
                        <ul class="small mb-0" style="color: #fef3c7; list-style: none; padding-left: 0;">
                            <li class="mb-1">• Spiritual growth and self-discovery</li>
                            <li class="mb-1">• Developing intuition and inner wisdom</li>
                            <li class="mb-1">• Teaching and sharing knowledge</li>
                            <li class="mb-1">• Finding balance between solitude and connection</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <!-- Historical Context & Famous Twin -->
        <div class="row g-4 mb-4">
            <!-- Day in History -->
            <?php if (!empty($dayInHistory)): ?>
            <div class="col-lg-6">
                <div class="rounded-4 p-4 shadow-lg border" style="background: linear-gradient(135deg, rgba(22, 163, 74, 0.2), rgba(5, 150, 105, 0.2)); backdrop-filter: blur(16px); border-color: rgba(34, 197, 94, 0.3) !important;">
                    <div class="d-flex align-items-center mb-4">
                        <div class="rounded-circle d-flex align-items-center justify-content-center me-3" style="width: 64px; height: 64px; background: linear-gradient(45deg, #4ade80, #10b981);">
                            <span class="fs-2">📅</span>
                        </div>
                        <div>
                            <h3 class="h4 fw-bold text-white mb-1">Your Day in History</h3>
                            <p class="mb-0" style="color: #86efac;">Significant events on your birthday</p>
                        </div>
                    </div>
                    
                    <div class="vstack gap-3">
                        <?php foreach ($dayInHistory as $event): ?>
                        <div class="rounded-3 p-3" style="background-color: rgba(34, 197, 94, 0.2);">
                            <div class="d-flex align-items-start gap-3">
                                <div class="rounded-circle mt-1 flex-shrink-0" style="width: 12px; height: 12px; background-color: #4ade80;"></div>
                                <div>
                                    <span class="fw-bold" style="color: #86efac;"><?php echo htmlspecialchars($event['year']); ?>:</span>
                                    <span style="color: #dcfce7;"><?php echo htmlspecialchars($event['event']); ?></span>
                                </div>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <?php endif; ?>

            <!-- Famous Birthday Twin -->
            <?php if ($famousTwin): ?>
            <div class="col-lg-6">
                <div class="rounded-4 p-4 shadow-lg border" style="background: linear-gradient(135deg, rgba(236, 72, 153, 0.2), rgba(244, 63, 94, 0.2)); backdrop-filter: blur(16px); border-color: rgba(244, 114, 182, 0.3) !important;">
                    <div class="d-flex align-items-center mb-4">
                        <div class="rounded-circle d-flex align-items-center justify-content-center me-3" style="width: 64px; height: 64px; background: linear-gradient(45deg, #f472b6, #f43f5e);">
                            <span class="fs-2">🌟</span>
                        </div>
                        <div>
                            <h3 class="h4 fw-bold text-white mb-1">Your Famous Birthday Twin</h3>
                            <p class="mb-0" style="color: #fbcfe8;">Shared cosmic energy</p>
                        </div>
                    </div>
                    
                    <div class="rounded-3 p-4" style="background-color: rgba(236, 72, 153, 0.2);">
                        <div class="d-flex align-items-center gap-3 mb-3">
                            <div class="rounded-circle d-flex align-items-center justify-content-center fs-2" style="width: 80px; height: 80px; background: linear-gradient(45deg, #f472b6, #f43f5e);">
                                👤
                            </div>
                            <div>
                                <div class="h5 fw-bold text-white mb-1"><?php echo htmlspecialchars($famousTwin['name']); ?></div>
                                <div style="color: #fbcfe8;"><?php echo htmlspecialchars($famousTwin['description'] ?? 'Celebrity'); ?></div>
                                <div class="small" style="color: #fce7f3;">Born: <?php echo htmlspecialchars($famousTwin['birth_date']); ?></div>
                            </div>
                        </div>
                        
                        <div class="rounded-3 p-3" style="background-color: rgba(236, 72, 153, 0.2);">
                            <h5 class="fw-semibold mb-2" style="color: #fbcfe8;">Shared Cosmic Traits:</h5>
                            <ul class="small mb-0" style="color: #fce7f3; list-style: none; padding-left: 0;">
                                <li class="mb-1">• Natural leadership abilities</li>
                                <li class="mb-1">• Strong intuitive powers</li>
                                <li class="mb-1">• Creative and innovative thinking</li>
                                <li class="mb-1">• Magnetic personality</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <?php endif; ?>
        </div>

        <!-- Action Buttons -->
        <div class="text-center">
            <div class="d-flex flex-column flex-sm-row gap-3 justify-content-center mb-4">
                <button onclick="downloadPDF()" class="btn text-white fw-bold py-3 px-4 rounded-3 d-flex align-items-center justify-content-center" style="background: linear-gradient(45deg, #10b981, #0d9488); border: none; transition: all 0.3s;">
                    <svg class="me-2" width="20" height="20" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                    </svg>
                    Download Full Report (PDF)
                </button>
                
                <button onclick="shareBlueprint()" class="btn text-white fw-bold py-3 px-4 rounded-3 d-flex align-items-center justify-content-center" style="background: linear-gradient(45deg, #3b82f6, #9333ea); border: none; transition: all 0.3s;">
                    <svg class="me-2" width="20" height="20" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.367 2.684 3 3 0 00-5.367-2.684z"></path>
                    </svg>
                    Share My Blueprint
                </button>
            </div>
            
            <p class="small" style="color: #c4b5fd;">
                Want to explore more? <a href="/" class="text-decoration-underline" style="color: #fbbf24; transition: color 0.3s;" onmouseover="this.style.color='#fde047'" onmouseout="this.style.color='#fbbf24'">Try another birthday</a> or 
                <a href="/compatibility" class="text-decoration-underline" style="color: #fbbf24; transition: color 0.3s;" onmouseover="this.style.color='#fde047'" onmouseout="this.style.color='#fbbf24'">check compatibility</a>
            </p>
        </div>
    </div>
</div>

<script>
function downloadPDF() {
    // Check if user is logged in
    <?php if (!isset($_SESSION['user_id'])): ?>
        alert('Please log in to download PDF. PDF download costs 2 credits.');
        window.location.href = '/login';
        return;
    <?php endif; ?>
    
    // Redirect to PDF download
    window.location.href = '/cosmic-snapshot/<?php echo $slug; ?>/download-pdf';
}

function shareBlueprint() {
    if (navigator.share) {
        navigator.share({
            title: 'Check out my Complete Cosmic Blueprint!',
            text: 'I just unlocked my full cosmic blueprint. Discover yours!',
            url: window.location.href
        }).catch(console.error);
    } else {
        navigator.clipboard.writeText(window.location.href).then(() => {
            alert('Link copied to clipboard! Share your cosmic blueprint with friends.');
        });
    }
}

// Add some visual effects
document.addEventListener('DOMContentLoaded', function() {
    // Animate elements on scroll
    const observerOptions = {
        threshold: 0.1,
        rootMargin: '0px 0px -50px 0px'
    };
    
    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.style.opacity = '1';
                entry.target.style.transform = 'translateY(0)';
            }
        });
    }, observerOptions);
    
    // Observe all major sections
    document.querySelectorAll('.shadow-lg').forEach(el => {
        el.style.opacity = '0';
        el.style.transform = 'translateY(20px)';
        el.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
        observer.observe(el);
    });
});
</script>