-- Create shareables table for SQLite
-- This table stores animated shareable content generated by users

CREATE TABLE IF NOT EXISTS shareables (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NULL,
    type TEXT NOT NULL CHECK (type IN ('cosmic', 'compatibility', 'rarity')),
    title TEXT NOT NULL,
    description TEXT,
    data TEXT NOT NULL, -- JSON data stored as TEXT in SQLite
    animation_config TEXT NOT NULL, -- JSON animation config stored as TEXT
    share_url TEXT NOT NULL,
    view_count INTEGER DEFAULT 0,
    download_count INTEGER DEFAULT 0,
    is_public INTEGER DEFAULT 1, -- SQLite uses INTEGER for BOOLEAN
    expires_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_shareables_user_id ON shareables(user_id);
CREATE INDEX IF NOT EXISTS idx_shareables_type ON shareables(type);
CREATE INDEX IF NOT EXISTS idx_shareables_share_url ON shareables(share_url);
CREATE INDEX IF NOT EXISTS idx_shareables_created_at ON shareables(created_at);
CREATE INDEX IF NOT EXISTS idx_shareables_expires_at ON shareables(expires_at);

-- Insert sample data for testing
INSERT OR IGNORE INTO shareables (user_id, type, title, description, data, animation_config, share_url) VALUES
(NULL, 'cosmic', 'Cosmic Snapshot - Virgo Rising', 'A beautiful animated cosmic snapshot for someone born under Virgo', 
 '{"zodiac_sign": "Virgo", "birth_date": "1990-09-15", "cosmic_elements": ["Earth", "Mercury"]}',
 '{"duration": 5000, "background": {"type": "gradient", "colors": ["#667eea", "#764ba2"], "animation": "pulse"}, "elements": [{"type": "zodiac_symbol", "symbol": "♍", "animation": "rotate_glow", "delay": 500}, {"type": "text", "content": "Virgo Rising", "style": "title", "animation": "fade_in", "delay": 1000}]}',
 '/shareables/1'),
(NULL, 'compatibility', 'Love Match - 89% Compatible', 'Animated compatibility report showing high compatibility',
 '{"person1": {"name": "Alex", "sign": "Leo"}, "person2": {"name": "Jordan", "sign": "Sagittarius"}, "score": 89}',
 '{"duration": 6000, "background": {"type": "gradient", "colors": ["#ff6b9d", "#c44569"], "animation": "pulse"}, "elements": [{"type": "heart", "animation": "heartbeat", "intensity": 0.89, "delay": 500}, {"type": "score_circle", "value": 89, "delay": 1500}, {"type": "text", "content": "Alex & Jordan", "style": "names", "animation": "slide_up", "delay": 2000}]}',
 '/shareables/2'),
(NULL, 'rarity', 'Ultra Rare Cosmic Blueprint', 'Animated rarity score showing legendary status',
 '{"rarity_level": "Legendary", "score": 97, "traits": ["Rare Moon Phase", "Unique Planetary Alignment"]}',
 '{"duration": 4000, "background": {"type": "cosmic_field", "rarity_level": "Legendary"}, "particles": {"type": "stars", "count": 50}, "elements": [{"type": "rarity_gem", "rarity": "Legendary", "delay": 500}, {"type": "score_counter", "target": 97, "delay": 1500}, {"type": "text", "content": "LEGENDARY", "style": "highlight", "animation": "bounce", "delay": 2500}]}',
 '/shareables/3');