-- Migration: Create shareables table
-- This table stores animated shareable content generated by users

CREATE TABLE IF NOT EXISTS shareables (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NULL,
    type ENUM('cosmic', 'compatibility', 'rarity') NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    data JSON NOT NULL,
    animation_config JSON NOT NULL,
    share_url VARCHAR(500) NOT NULL,
    view_count INT DEFAULT 0,
    download_count INT DEFAULT 0,
    is_public BOOLEAN DEFAULT TRUE,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_user_id (user_id),
    INDEX idx_type (type),
    INDEX idx_share_url (share_url),
    INDEX idx_created_at (created_at),
    INDEX idx_expires_at (expires_at),
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Add some sample data for testing
INSERT INTO shareables (user_id, type, title, description, data, animation_config, share_url) VALUES
(NULL, 'cosmic', 'Cosmic Snapshot - Virgo Rising', 'A beautiful animated cosmic snapshot for someone born under Virgo', 
 '{"zodiac_sign": "Virgo", "birth_date": "1990-09-15", "cosmic_elements": ["Earth", "Mercury"]}',
 '{"duration": 5000, "background": {"type": "gradient", "colors": ["#667eea", "#764ba2"], "animation": "pulse"}, "elements": [{"type": "zodiac_symbol", "symbol": "♍", "animation": "rotate_glow", "delay": 500}, {"type": "text", "content": "Virgo Rising", "style": "title", "animation": "fade_in", "delay": 1000}]}',
 '/shareables/1'),
(NULL, 'compatibility', 'Love Match - 89% Compatible', 'Animated compatibility report showing high compatibility',
 '{"person1": {"name": "Alex", "sign": "Leo"}, "person2": {"name": "Jordan", "sign": "Sagittarius"}, "score": 89}',
 '{"duration": 6000, "background": {"type": "gradient", "colors": ["#ff6b9d", "#c44569"], "animation": "pulse"}, "elements": [{"type": "heart", "animation": "heartbeat", "intensity": 0.89, "delay": 500}, {"type": "score_circle", "value": 89, "delay": 1500}, {"type": "text", "content": "Alex & Jordan", "style": "names", "animation": "slide_up", "delay": 2000}]}',
 '/shareables/2'),
(NULL, 'rarity', 'Ultra Rare Cosmic Blueprint', 'Animated rarity score showing legendary status',
 '{"rarity_level": "Legendary", "score": 97, "traits": ["Rare Moon Phase", "Unique Planetary Alignment"]}',
 '{"duration": 4000, "background": {"type": "cosmic_field", "rarity_level": "Legendary"}, "particles": {"type": "stars", "count": 50}, "elements": [{"type": "rarity_gem", "rarity": "Legendary", "delay": 500}, {"type": "score_counter", "target": 97, "delay": 1500}, {"type": "text", "content": "LEGENDARY", "style": "highlight", "animation": "bounce", "delay": 2500}]}',
 '/shareables/3');